import { Media, MediaFilter, MediaType, SortOption } from '../models/media.model';
import { TrendingUpIcon } from '../shared/icons/actions/trending-up';
import { Icons } from '../shared/icons/icons';
import { FilmIcon } from '../shared/icons/media/film';
import { TvIcon } from '../shared/icons/media/tv';
import { VideoDocumentaryIcon } from '../shared/icons/media/video-documentary';
import { CalendarIcon } from '../shared/icons/ui/calendar';
import { StarIcon } from '../shared/icons/ui/star';
import type { SectionId, CategoryMeta, WeeklySectionMeta } from '../types/navigation.types';

export const SECTION_DOM_IDS: Record<SectionId, string> = {
  hero: 'hero-section',
  weekly: 'section-weekly',
  trending: 'section-trending',
  movies: 'section-category',
  series: 'section-category',
  documentary: 'section-category',
  category: 'section-category',
};

export const HERO_FILTER_IDS: MediaFilter[] = [
  'all',
  'movie',
  'series',
  'documentary',
];

export const NAV_LINK_IDS: Array<{ id: SectionId; icon: Icons }> = [
  { id: 'movies', icon: FilmIcon },
  { id: 'series', icon: TvIcon },
  { id: 'documentary', icon: VideoDocumentaryIcon },
  { id: 'trending', icon: TrendingUpIcon },
];

export const BOTTOM_NAV_IDS: Array<{ id: SectionId; icon: Icons }> = [
  { id: 'hero', icon: FilmIcon },
  { id: 'movies', icon: FilmIcon },
  { id: 'series', icon: TvIcon },
  { id: 'trending', icon: TrendingUpIcon },
];

export const CATEGORY_METAS: CategoryMeta[] = [
  { id: 'all', icon: FilmIcon, accent: 'violet' },
  { id: 'movie', icon: FilmIcon, accent: 'violet' },
  { id: 'series', icon: TvIcon, accent: 'blue' },
  { id: 'documentary', icon: VideoDocumentaryIcon, accent: 'green' },
];

export const SORT_OPTION_IDS: Array<{ id: SortOption; icon: Icons }> = [
  { id: 'popularity', icon: TrendingUpIcon },
  { id: 'release', icon: CalendarIcon },
  { id: 'rating', icon: StarIcon },
];

export const WEEKLY_SECTIONS_META: WeeklySectionMeta[] = [
  { key: 'movies', accent: 'violet', type: 'movie' },
  { key: 'series', accent: 'blue', type: 'series' },
  { key: 'docs', accent: 'green', type: 'documentary' },
];

export const allMedia: Media[] = [
  {
    id: 1,
    title: 'Stellar Collapse',
    type: 'movie',
    genres: ['Sci-Fi', 'Thriller'],
    rating: 8.4,
    year: 2026,
    poster: 'https://images.unsplash.com/photo-1733592688551-5ba7804a9634?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1562619425-c307bb83bc42?w=1400&q=80',
    streaming: ['Netflix', 'Apple TV+'],
    description: 'A lone astronaut discovers that the universe is collapsing from the inside out and must race against time to warn humanity.',
    duration: '2h 18m',
    trending: true,
    weeklyRelease: true,
    trendingRank: 1,
  },
  {
    id: 2,
    title: 'Dark Covenant',
    type: 'movie',
    genres: ['Horror', 'Supernatural'],
    rating: 7.9,
    year: 2026,
    poster: 'https://images.unsplash.com/photo-1760577315790-3a0ed3f42496?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1762554915502-7ce95effe4ee?w=1400&q=80',
    streaming: ['HBO Max', 'Prime Video'],
    description: 'When a small town unearths an ancient pact made with a forgotten god, the residents begin to transform one by one.',
    duration: '1h 54m',
    weeklyRelease: true,
    trending: true,
    trendingRank: 3,
  },
  {
    id: 3,
    title: 'The Last Detective',
    type: 'movie',
    genres: ['Crime', 'Drama', 'Mystery'],
    rating: 8.1,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1759829381324-f3d2b5ed7f6d?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1732349234249-1b5b59368c77?w=1400&q=80',
    streaming: ['Hulu', 'Netflix'],
    description: 'A retired detective is pulled back into the underworld when his daughter vanishes without a trace during a city-wide blackout.',
    duration: '2h 05m',
    weeklyRelease: true,
  },
  {
    id: 4,
    title: 'Iron Kingdom',
    type: 'movie',
    genres: ['Action', 'Fantasy', 'Adventure'],
    rating: 7.6,
    year: 2026,
    poster: 'https://images.unsplash.com/photo-1764069488362-d64a596448f0?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1767709879762-c7a6ce819aeb?w=1400&q=80',
    streaming: ['Disney+', 'Prime Video'],
    description: 'An exiled warrior returns to reclaim his throne from a sorcerer who has bent the kingdom to ruin.',
    duration: '2h 32m',
    trending: true,
    weeklyRelease: true,
    trendingRank: 5,
  },
  {
    id: 5,
    title: 'Neon Requiem',
    type: 'movie',
    genres: ['Sci-Fi', 'Action', 'Cyberpunk'],
    rating: 8.7,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1631208298935-ff6d844c4771?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1631208298935-ff6d844c4771?w=1400&q=80',
    streaming: ['Netflix'],
    description: "In a rain-soaked megalopolis run by corporate AIs, a hacker discovers she's the key to either humanity's freedom or its extinction.",
    duration: '2h 09m',
    trending: true,
    trendingRank: 2,
  },
  {
    id: 6,
    title: 'Samurai Protocol',
    type: 'movie',
    genres: ['Action', 'Historical', 'Drama'],
    rating: 8.3,
    year: 2026,
    poster: 'https://images.unsplash.com/photo-1754474419533-7e2eb0e6fa60?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1754474419533-7e2eb0e6fa60?w=1400&q=80',
    streaming: ['Apple TV+', 'Hulu'],
    description: 'A dying samurai trains one final student before confronting the warlord who destroyed his clan.',
    duration: '1h 58m',
    weeklyRelease: true,
  },
  {
    id: 7,
    title: 'Echo Protocol',
    type: 'movie',
    genres: ['Sci-Fi', 'Thriller', 'Drama'],
    rating: 7.8,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1773067752197-826607e11a20?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1733592688551-5ba7804a9634?w=1400&q=80',
    streaming: ['Prime Video'],
    description: 'When a corporation releases android workers with suppressed emotions, one unit starts to feel and fight back.',
    duration: '1h 47m',
  },
  {
    id: 8,
    title: 'Crimson Facade',
    type: 'movie',
    genres: ['Thriller', 'Drama', 'Psychological'],
    rating: 8.0,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1634826831087-24d042ea76fd?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1634826831087-24d042ea76fd?w=1400&q=80',
    streaming: ['Netflix', 'Hulu'],
    description: 'A forensic psychologist enters the mind of a serial killer only to realize she may be next.',
    duration: '1h 51m',
  },
  {
    id: 9,
    title: 'Veil of Empires',
    type: 'series',
    genres: ['Fantasy', 'Drama', 'Epic'],
    rating: 9.1,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1767709879762-c7a6ce819aeb?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1764069488362-d64a596448f0?w=1400&q=80',
    streaming: ['HBO Max'],
    description: 'Seven royal houses clash for dominion over a crumbling continent as an ancient evil stirs beneath the earth.',
    seasons: 2,
    episodes: 16,
    trending: true,
    weeklyRelease: true,
    trendingRank: 4,
  },
  {
    id: 10,
    title: 'Grid City',
    type: 'series',
    genres: ['Crime', 'Thriller', 'Neo-Noir'],
    rating: 8.6,
    year: 2026,
    poster: 'https://images.unsplash.com/photo-1732349234249-1b5b59368c77?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1759829381324-f3d2b5ed7f6d?w=1400&q=80',
    streaming: ['Netflix', 'Prime Video'],
    description: 'A maverick detective navigates a corrupt metropolis using illegal surveillance tech to solve cases the system ignores.',
    seasons: 3,
    episodes: 30,
    weeklyRelease: true,
    trending: true,
    trendingRank: 6,
  },
  {
    id: 11,
    title: 'Signal Lost',
    type: 'series',
    genres: ['Sci-Fi', 'Mystery', 'Supernatural'],
    rating: 8.2,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1562619425-c307bb83bc42?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1733592688551-5ba7804a9634?w=1400&q=80',
    streaming: ['Apple TV+'],
    description: 'A remote space relay station begins receiving messages from an unknown civilization, but the crew starts disappearing.',
    seasons: 1,
    episodes: 8,
    weeklyRelease: true,
  },
  {
    id: 12,
    title: 'The Mourning Hour',
    type: 'series',
    genres: ['Horror', 'Drama', 'Supernatural'],
    rating: 7.7,
    year: 2026,
    poster: 'https://images.unsplash.com/photo-1762554915502-7ce95effe4ee?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1760577315790-3a0ed3f42496?w=1400&q=80',
    streaming: ['Shudder', 'Prime Video'],
    description: 'A grief therapist moves to a small coastal town and discovers that the spirits of the dead are trapped there, waiting.',
    seasons: 2,
    episodes: 14,
    weeklyRelease: true,
  },
  {
    id: 13,
    title: 'Parallax',
    type: 'series',
    genres: ['Sci-Fi', 'Action', 'Spy'],
    rating: 8.8,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1773067752197-826607e11a20?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1631208298935-ff6d844c4771?w=1400&q=80',
    streaming: ['Disney+'],
    description: 'A covert agent can jump between parallel timelines, but each jump makes it harder to find her way back home.',
    seasons: 1,
    episodes: 10,
  },
  {
    id: 14,
    title: 'Hollow Throne',
    type: 'series',
    genres: ['Action', 'Fantasy', 'Shonen'],
    rating: 9.3,
    year: 2026,
    poster: 'https://images.unsplash.com/photo-1613487971624-24f87ffdbfc5?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1631208298935-ff6d844c4771?w=1400&q=80',
    streaming: ['Crunchyroll', 'Netflix'],
    description: 'In a world where gods walk among humans, a powerless boy inherits the cursed blade that can slay them all.',
    seasons: 2,
    episodes: 48,
    trending: true,
    weeklyRelease: true,
    trendingRank: 7,
  },
  {
    id: 15,
    title: 'Void Architects',
    type: 'series',
    genres: ['Sci-Fi', 'Mecha', 'Drama'],
    rating: 8.9,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1733592688551-5ba7804a9634?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1562619425-c307bb83bc42?w=1400&q=80',
    streaming: ['Netflix', 'Crunchyroll'],
    description: "Humanity's last defense against alien architects are enormous bio-mechs piloted by genetically engineered teens.",
    seasons: 3,
    episodes: 72,
    weeklyRelease: true,
  },
  {
    id: 16,
    title: 'Midnight Shogun',
    type: 'series',
    genres: ['Action', 'Historical', 'Supernatural'],
    rating: 8.5,
    year: 2026,
    poster: 'https://images.unsplash.com/photo-1754474419533-7e2eb0e6fa60?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1754474419533-7e2eb0e6fa60?w=1400&q=80',
    streaming: ['Crunchyroll'],
    description: "A cursed ronin wielding a demon-possessed blade navigates feudal Japan's bloodiest era and its supernatural horrors.",
    seasons: 1,
    episodes: 24,
    weeklyRelease: true,
  },
  {
    id: 17,
    title: 'Abyss Protocol',
    type: 'series',
    genres: ['Psychological', 'Thriller', 'Mystery'],
    rating: 9.0,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1634826831087-24d042ea76fd?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1634826831087-24d042ea76fd?w=1400&q=80',
    streaming: ['Netflix'],
    description: 'A detective with the ability to see memory echoes investigates murders that appear to be committed by ghosts.',
    seasons: 2,
    episodes: 26,
  },
  {
    id: 18,
    title: 'Beneath the Surface',
    type: 'documentary',
    genres: ['Nature', 'Ocean', 'Science'],
    rating: 9.2,
    year: 2026,
    poster: 'https://images.unsplash.com/photo-1772436756283-c277ec0dd863?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1772436756283-c277ec0dd863?w=1400&q=80',
    streaming: ['Netflix', 'Disney+'],
    description: 'Groundbreaking footage from the deepest ocean trenches reveals species never before documented by science.',
    duration: '1h 42m',
    trending: true,
    weeklyRelease: true,
    trendingRank: 8,
  },
  {
    id: 19,
    title: 'Fire & Earth',
    type: 'documentary',
    genres: ['Nature', 'Environment', 'Science'],
    rating: 8.8,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1713976047691-cac4d1f4fc05?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1713976047691-cac4d1f4fc05?w=1400&q=80',
    streaming: ['Apple TV+', 'Prime Video'],
    description: 'Witness the devastating power of volcanoes, earthquakes, and floods through immersive on-the-ground filming.',
    duration: '1h 58m',
    weeklyRelease: true,
  },
  {
    id: 20,
    title: 'Wild Corridors',
    type: 'documentary',
    genres: ['Nature', 'Wildlife', 'Conservation'],
    rating: 9.0,
    year: 2026,
    poster: 'https://images.unsplash.com/photo-1763675848693-524da805aaca?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1763675848693-524da805aaca?w=1400&q=80',
    streaming: ['Disney+', 'BBC iPlayer'],
    description: 'Following the extraordinary seasonal migrations of wildlife across three continents over four years.',
    duration: '2h 12m',
    weeklyRelease: true,
    trending: true,
    trendingRank: 9,
  },
  {
    id: 21,
    title: 'The Hidden Code',
    type: 'documentary',
    genres: ['Technology', 'Society', 'Investigation'],
    rating: 8.4,
    year: 2025,
    poster: 'https://images.unsplash.com/photo-1761845064537-929979725425?w=400&q=80',
    backdrop: 'https://images.unsplash.com/photo-1767066973428-b7d56f879ed8?w=1400&q=80',
    streaming: ['Netflix'],
    description: 'A chilling investigation into how algorithmic manipulation shapes elections, economies, and human behavior.',
    duration: '1h 38m',
  },
];

export const streamingBrandColors: Record<string, string> = {
  Netflix: '#dc2626',
  'HBO Max': '#6d28d9',
  'Prime Video': '#3b82f6',
  'Apple TV+': '#374151',
  'Disney+': '#1d4ed8',
  Hulu: '#16a34a',
  Crunchyroll: '#f97316',
  Shudder: '#7f1d1d',
  'BBC iPlayer': '#b91c1c',
};

export const getByType = (type: MediaFilter): Media[] =>
  type === 'all' ? allMedia : allMedia.filter((item) => item.type === type);

export const getTrending = (): Media[] =>
  allMedia
    .filter((item) => item.trending)
    .sort((a, b) => (a.trendingRank ?? 99) - (b.trendingRank ?? 99));

export const getWeeklyReleases = (type?: MediaType): Media[] =>
  allMedia.filter((item) => item.weeklyRelease && (!type || item.type === type));

export const getRandomRecommendation = (
  type: MediaFilter,
  exclude?: number,
): Media => {
  const pool = type === 'all' ? allMedia : allMedia.filter((item) => item.type === type);
  const filtered = exclude == null ? pool : pool.filter((item) => item.id !== exclude);
  const index = Math.floor(Math.random() * filtered.length);
  return filtered[index] ?? allMedia[0];
};
